# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_nth <- function(xa, middle) {
    .Call(`_Qlab_find_nth`, xa, middle)
}

c_iter_kk <- function(c1, c2, i2, imax, value) {
    .Call(`_Qlab_c_iter_kk`, c1, c2, i2, imax, value)
}

c_order_nv <- function(vec) {
    .Call(`_Qlab_c_order_nv`, vec)
}

c_order <- function(vec) {
    .Call(`_Qlab_c_order`, vec)
}

getIntervals <- function(vec_a, vec_b, k, Imin) {
    .Call(`_Qlab_getIntervals`, vec_a, vec_b, k, Imin)
}

